---
title: Template for preparing your manuscript submission to Copernicus journals using RMarkdown
journal: "`r rticles::copernicus_journal_abbreviations(journal_name = 'communication')`"
author:
    # authors can have multiple affiliations, which can also be used to mark deceased coauthors
  - given_name: Daniel
    surname: Nüst
    affiliation: "1, *"
    email: daniel.nuest@uni-muenster.de
    corresponding: true
  - given_name: Josiah
    surname: Carberry
    affiliation: 2
    email: j.carberry@orcid.org
  - given_name: Markus
    surname: Konkol
    affiliation: "1, *"
  - given_name: Nikolaus
    surname: Copernicus
    affiliation: "3, †"
# If you have more than one corresponding author, add them manually using the following structure (note the commas):
# Two authors: Daniel Nüst (daniel.nuest@uni-muenster.de) and Josiah Carberry (j.carberry@orcid.org)
# Three authors or more: Daniel Nüst (daniel.nuest@uni-muenster.de), Josiah Carberry (j.carberry@orcid.org), and Markus Konkol (m.konkol@wwu.de)
# If the following line is uncommented, the "corresponding: true" above are ignored
#correspongdingauthors: Daniel Nüst (daniel.nuest@uni-muenster.de) and Josiah Carberry (j.carberry@orcid.org)
# If authors contributed equally, please mark the respective author names with an asterisk '*' and add a further affiliation: 'These authors contributed equally to this work.'", see template.
affiliation:
  - code: 1
    address: Institute for Geoinformatics, University of Münster, 48149 Münster, Germany
  - code: 2
    address: Psychoceramics, Wesleyan University, Middletown, CT, United States
  - code: 3
    address: University of Ferrara, Ferrara, Italy
  - code: "†"
    address: deceased, 24 May 1543
  - code: "*"
    address: These authors contributed equally to this work.
abstract: |
  The abstract goes here.
  It can also be on _multiple lines_.
bibliography: sample.bib
running:
  title: R Markdown Template for Copernicus
  author: Nüst et al.
competinginterests: |
  The authors declare no competing interests.
# See https://publications.copernicus.org/for_authors/licence_and_copyright.html, normally used for transferring the copyright, if needed. 
# Note: additional copyright statements for affiliated software or data need to be placed in the data availability section. 
copyrightstatement: |
  The author's copyright for this publication is transferred to institution/company. 
### Note: unless stated otherwise, software and data affiliated with the manuscript are assumed to be published under the same licence as the article (currently Creative Commons 4.0)
availability:
  #  use this to add a statement when having only software code available
  #  use this to add a statement when having only data sets available
  #code: |
  #data: |
  codedata: |
    use this to add a statement when having data sets and software code available
  sample: |
    use this section when having geoscientific samples available
videosupplement: |
  use this section when having video supplements available
authorcontribution: |
  Daniel wrote the package. Josiah thought about poterry. Markus filled in for a second author.
disclaimer: |
  We like Copernicus.
acknowledgements: |
  Thanks to the rticles contributors!
appendix: |
  \section{Figures and tables in appendices}
  \subsection{Option 1}
  If you sorted all figures and tables into the sections of the text, please also sort the appendix figures and appendix tables into the respective appendix sections.
  They will be correctly named automatically.
  \subsection{Option 2}
  If you put all figures after the reference list, please insert appendix tables and figures after the normal tables and figures.
  
  `\appendixfigures` needs to be added in front of appendix figures
  `\appendixtables` needs to be added in front of appendix tables
  
  Please add `\clearpage` between each table and/or figure. Further guidelines on figures and tables can be found below.
  Regarding figures and tables in appendices, the following two options are possible depending on your general handling of figures and tables in the manuscript environment:
  To rename them correctly to A1, A2, etc., please add the following commands in front of them:
output:
  rticles::copernicus_article: 
    highlight: NULL
    keep_tex: true
  bookdown::pdf_book:
    base_format: rticles::copernicus_article # for using bookdown features like \@ref()
editor_options: 
  markdown: 
    wrap: 72
---

\introduction[Introduction]

Introduction text goes here. You can change the name of the section if
necessary using `\introduction[modified heading]`.

The following settings can or must be configured in the header of this
file and are bespoke for Copernicus manuscripts:

-   The `journal` you are submitting to using the official abbreviation.
    You can use the function
    `rticles::copernicus_journal_abbreviations(name = '...')` to search
    the existing journals.

-   Specific sections of the manuscript:

    -   `running` with `title` and `author`

    -   `competinginterests`

    -   `copyrightstatement` (optional)

    -   `availability` (strongly recommended if any used), one of
        `code`, `data`, or `codedata`

    -   `authorcontribution`

    -   `disclaimer`

    -   `acknowledgements`

See the defaults and examples from the skeleton and the official
Copernicus documentation for details.

**Please note:** Per [their
guidelines](https://publications.copernicus.org/for_authors/manuscript_preparation.html),
Copernicus does not support additional \LaTeX{} packages or new \LaTeX{}
commands than those defined in their `.cls` file. This means that you
cannot add any extra dependencies and a warning will be thrown if so.\
This extends to syntax highlighting of source code. Therefore this
template sets the parameter `highlight` in the YAML header to `NULL` to
deactivate Pandoc syntax highlighter. This prevent addition of external
packages for highlighting inserted by Pandoc. However, it might be
desirable to have syntax highlight available in preprints or for others
reasons. Please see `?rmarkdown::pdf_document` for available options to
activate highlighting.

**Important**: Always double-check with the official manuscript
preparation guidelines at
<https://publications.copernicus.org/for_authors/manuscript_preparation.html>,
especially the sections "Technical instructions for LaTeX" and
"Manuscript composition". Please contact Daniel Nüst,
`daniel.nuest@uni-muenster.de`, with any problems.

# Content section one

## Subsection Heading Here

Subsection text here.

### Subsubsection Heading Here

Subsubsection text here.

# Content section with citations

See the [R Markdown docs for bibliographies and
citations](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html).

Copernicus supports biblatex and a sample bibliography is in file
`sample.bib`. Read [@ahlstromDominantRoleSemiarid2015a], and [see
@ainsworthResponsePhotosynthesisStomatal2007].

[@ahlstromDominantRoleSemiarid2015a]

a;dlskjf [@medlynUsingModelsGuide2016c;
@mooreReviewsSynthesesAustralian2016]

\conclusions[Conclusions]

The conclusion goes here.
